"""Application ports — implemented by adapters, consumed by use-cases."""

from __future__ import annotations

from typing import Any, Optional, Protocol


class SessionStore(Protocol):
    def is_authenticated(self) -> bool: ...

    def set_authenticated(self, value: bool) -> None: ...

    def get_arduino_synced(self) -> bool: ...

    def set_arduino_synced(self, value: bool) -> None: ...

    def get_light(self) -> bool: ...

    def set_light(self, value: bool) -> None: ...

    def get_music(self) -> bool: ...

    def set_music(self, value: bool) -> None: ...

    def get_temperature(self) -> float | None: ...

    def set_temperature(self, value: float | None, *, fresh: bool) -> None: ...

    def set_recognition(
        self, user: str, command: str, confidence: float
    ) -> None: ...

    def get_last_user(self) -> str: ...

    def set_last_user(self, user: str) -> None: ...

    def get_last_command(self) -> str: ...

    def get_confidence(self) -> float: ...


class SerialPort(Protocol):
    def send_command(self, command: str) -> bool: ...

    def request_temperature(self, timeout_s: float = 2.0) -> Optional[float]: ...

    def connect(self, port: str | None = None) -> bool: ...

    def disconnect(self) -> None: ...

    def is_connected(self) -> bool: ...

    def resolve_port(self) -> Optional[str]: ...


class MusicPlayer(Protocol):
    def start(self) -> bool: ...

    def stop(self) -> None: ...


class VoiceGateway(Protocol):
    def verify_password(self, audio_path: str) -> Any: ...

    def predict_command(self, audio_path: str) -> dict[str, Any]: ...


class AudioRecorder(Protocol):
    def record(self) -> str: ...
